---
- name: Google Chrome
  download_url: "https://www.google.com/chrome/thank-you.html?hl=en-US&brand=CHBD&installdata=offline,chrome&os=Windows"

- name: Firefox
  download_url: "https://www.mozilla.org/en-US/firefox/new/"

- name: VLC Media Player
  download_url: "https://www.videolan.org/vlc/download-windows.html"

